"""Merge content/glossary/*.yaml into content/glossary.json (read by the site) and validate it.

Entry format (docs/GLOSSARY.md):
  - id: fraction
    en: fraction
    fa-IR: کسر
    fa-AF: کسر
    ps: کسر
    src: { fa-IR: "G03_riazi_sevom ch3", fa-AF: "AF_G05_riazi p.95", ps: "AF_G05_riazi_ps p.95" }
    status: { fa-AF: draft, ps: draft }    # reviewed once a native teacher signs off
    note: optional free text

Usage: .venv/bin/python tools/build_glossary.py   (exit 1 on errors)
"""
import glob, json, os, re, sys
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCALES = ("fa-IR", "fa-AF", "ps", "en")
ARABIC_SCRIPT = re.compile(r"[؀-ۿ]")


def main():
    terms, errors = [], []
    for f in sorted(glob.glob(os.path.join(ROOT, "content/glossary/*.yaml"))):
        for t in yaml.safe_load(open(f, encoding="utf-8")) or []:
            t["_file"] = os.path.basename(f)
            terms.append(t)
    seen = {}
    for t in terms:
        tid = t.get("id", "?")
        if tid in seen:
            errors.append(f"duplicate id {tid} ({seen[tid]}, {t['_file']})")
        seen[tid] = t["_file"]
        for loc in ("fa-IR", "en"):
            if not t.get(loc):
                errors.append(f"{tid}: missing {loc}")
        for loc in ("fa-IR", "fa-AF", "ps"):
            if t.get(loc) and not ARABIC_SCRIPT.search(t[loc]):
                errors.append(f"{tid}: {loc} is not in Persian/Arabic script")
        if t.get("en") and ARABIC_SCRIPT.search(t["en"]):
            errors.append(f"{tid}: en contains Persian/Arabic script")
    out = {
        "_note": "Generated by tools/build_glossary.py from content/glossary/*.yaml. Do not edit by hand.",
        "terms": [
            {k: t[k] for k in ("id", *LOCALES, "status") if t.get(k)}
            for t in sorted(terms, key=lambda t: t["id"])
        ],
    }
    json.dump(out, open(os.path.join(ROOT, "content/glossary.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    n = len(terms)
    filled = {loc: sum(1 for t in terms if t.get(loc)) for loc in LOCALES}
    print(f"{n} terms; filled: " + ", ".join(f"{loc} {filled[loc]}" for loc in LOCALES))
    for e in errors:
        print("ERROR", e)
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
